name: WebMethods.io Asset Puller

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      environment:
        description: 'Environment to pull assets from'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - dev
          - prod

jobs:
  pull-assets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Create assets directory
        run: mkdir -p assets/workflows assets/flows assets/listeners assets/messaging
      
      - name: Verify directory exists
        run: |
          if [ -d "assets/workflows" ]; then
            echo "Directory created successfully."
          else
            echo "Directory creation failed."
            exit 1
          fi
          
      - name: Print working directory
        run: pwd
      
      - name: Verify directories
        run: |
          ls -l assets
          ls -l assets/workflows

      # Create a config file with the correct path
      - name: Create config file
        run: |
          cat > config.json << 'EOL'
          {
            "base_url": "${{ vars.WEBMETHODS_BASE_URL }}",
            "project_name": "${{ vars.WEBMETHODS_PROJECT_NAME }}",
            "project_id": "${{ vars.WEBMETHODS_PROJECT_ID }}",
            "github_repo_path": "./assets",
            "auth": {
              "api_key": "${{ secrets.WEBMETHODS_API_KEY }}"
            }
          }
          EOL

      - name: List contents before commit and push
        run: ls -R assets

      - name: Run asset puller
        run: |
          python webmethods_asset_puller.py
          # Create placeholder files if directories are empty
          touch assets/workflows/.gitkeep
          touch assets/flows/.gitkeep
          touch assets/listeners/.gitkeep
          touch assets/messaging/.gitkeep
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f assets/
          git add config.json || echo "No config.json changes"
          git add webmethods_asset_puller.log || echo "No log file to add"
          git status
          git commit -m "Update webMethods.io assets [skip ci]" || echo "No changes to commit"
      
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets/ webmethods_asset_puller.log config.json'
          message: 'Update webMethods.io assets [skip ci]'
          default_author: github_actionsname: WebMethods.io Asset Puller

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      environment:
        description: 'Environment to pull assets from'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - dev
          - prod

jobs:
  pull-assets:
    runs-on: ubuntu-latest
    defaults:
      run:
        # This explicitly sets the working directory to the repository root
        # regardless of the actual path on the runner
        working-directory: ${{ github.workspace }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Print GitHub workspace
        run: echo "GitHub workspace is ${{ github.workspace }}"
      
      - name: Print current directory
        run: pwd
      
      - name: Create assets directory
        run: mkdir -p assets/workflows assets/flows assets/listeners assets/messaging
      
      - name: Verify directory exists
        run: |
          if [ -d "assets/workflows" ]; then
            echo "Directory created successfully."
          else
            echo "Directory creation failed."
            exit 1
          fi
      
      - name: Verify directories
        run: |
          ls -l assets
          ls -l assets/workflows

      # Create a config file with the correct path
      - name: Create config file
        run: |
          cat > config.json << 'EOL'
          {
            "base_url": "${{ vars.WEBMETHODS_BASE_URL }}",
            "project_name": "${{ vars.WEBMETHODS_PROJECT_NAME }}",
            "project_id": "${{ vars.WEBMETHODS_PROJECT_ID }}",
            "github_repo_path": "${{ github.workspace }}/assets",
            "auth": {
              "api_key": "${{ secrets.WEBMETHODS_API_KEY }}"
            }
          }
          EOL
          echo "Created config file with path: ${{ github.workspace }}/assets"
          cat config.json

      - name: List contents before commit and push
        run: ls -R assets

      - name: Run asset puller
        run: |
          python webmethods_asset_puller.py
          # Create placeholder files if directories are empty
          touch assets/workflows/.gitkeep
          touch assets/flows/.gitkeep
          touch assets/listeners/.gitkeep
          touch assets/messaging/.gitkeep
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f assets/
          git add config.json || echo "No config.json changes"
          git add webmethods_asset_puller.log || echo "No log file to add"
          git status
          git commit -m "Update webMethods.io assets [skip ci]" || echo "No changes to commit"
      
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets/ webmethods_asset_puller.log config.json'
          message: 'Update webMethods.io assets [skip ci]'
          default_author: github_actions

      - name: List contents After commit and push
        run: ls -R assets

# Made with Bob


      - name: List contents After commit and push
        run: ls -R assets

# Made with Bob
