name: WebMethods.io Asset Puller

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      environment:
        description: 'Environment to pull assets from'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - dev
          - prod

jobs:
  pull-assets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Create config file
        run: |
          cat > config.json << EOF
          {
            "base_url": "${{ secrets.WEBMETHODS_BASE_URL }}",
            "project_name": "${{ secrets.WEBMETHODS_PROJECT_NAME }}",
            "project_id": "${{ secrets.WEBMETHODS_PROJECT_ID }}",
            "github_repo_path": "./assets",
            "auth": {
              "api_key": "${{ secrets.WEBMETHODS_API_KEY }}"
            }
          }
          EOF
      
      - name: Run asset puller
        run: python webmethods_asset_puller.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/
          git add config.json || echo "No config.json changes"
          git add webmethods_asset_puller.log || echo "No log file to add"
          git commit -m "Update webMethods.io assets [skip ci]" || echo "No changes to commit"
          
          # Use PAT for authentication
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push

# Made with Bob
